# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 08:25
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recruitment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91xxxxxxxxxx'", regex='^\\+?1?\\d{9,15}$')])),
                ('current_designation', models.CharField(max_length=100)),
                ('current_employer', models.CharField(max_length=100)),
                ('current_ctc', models.PositiveIntegerField()),
                ('expected_ctc', models.PositiveIntegerField()),
                ('notice_period', models.PositiveIntegerField()),
                ('total_exp_yrs', models.PositiveIntegerField()),
                ('total_exp_mts', models.PositiveIntegerField()),
                ('highest_qual', models.CharField(max_length=100)),
                ('college_highest_qual', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to=recruitment.models.get_upload_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted')], default='Pending', max_length=20)),
                ('comment', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('min_salary', models.PositiveIntegerField()),
                ('max_salary', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('min_requirement', models.TextField()),
                ('job_description', models.TextField()),
                ('posting_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.JobOpening'),
        ),
    ]
