# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_candidate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='about_company',
            field=models.TextField(default=datetime.datetime(2016, 5, 14, 8, 30, 29, 225130, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
