# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import recruitment.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_jobopening_about_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('cont_no', models.CharField(max_length=20)),
                ('job_description', models.TextField()),
                ('further_info', models.FileField(upload_to=recruitment.models.get_upload_file_name)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
